---
- name: build frontend bundle
  command:
    cmd: npm run build
    chdir: "{{ source_path }}/frontend"
  delegate_to: localhost

- name: create deploy directory
  become: true
  file:
    path: "{{ deploy_path }}/ui"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: upload application
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ source_path }}/{{ item }}"
    dest: "{{ deploy_path }}/ui"
  loop:
    - backend/Pipfile
    - backend/Pipfile.lock
    - backend/ptinsight
    - frontend/dist
  notify:
    - restart UI service

- name: create config directory
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ui/backend/config"
    state: directory

- name: upload config
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: ui.yaml.j2
    dest: "{{ deploy_path }}/ui/backend/config/ui.yaml"
  notify:
    - restart UI service

- name: Copy UI service file
  become: true
  template:
    src: ptinsight-ui.service.j2
    dest: /usr/lib/systemd/system/ptinsight-ui.service

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: install dependencies
  become: true
  become_user: "{{ deploy_user }}"
  command: 
    cmd: pipenv sync
    chdir: "{{ deploy_path }}/ui/backend"

- meta: flush_handlers

- name: start the UI service
  become: true
  service:
    name: ptinsight-ui
    state: started
    enabled: yes
