---
- name: build frontend bundle
  run_once: true
  shell:
    cmd: PATH=/bin:$PATH && NVM_DIR=~/.nvm && . "$NVM_DIR/nvm.sh" && nvm use node && npm install && npm run build
    chdir: "{{ source_path }}/frontend"
    executable: /bin/bash
  delegate_to: localhost

- name: create frontend deploy directory
  become: true
  file:
    path: "{{ deploy_path }}/ui/frontend"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: upload frontend
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ source_path }}/frontend/{{ item }}"
    dest: "{{ deploy_path }}/ui/frontend"
  loop:
    - dist
  notify:
    - restart UI service

- name: build ptinsight-ui
  run_once: true
  command:
    cmd: poetry build --format=wheel
    chdir: "{{ source_path }}/backend"
  delegate_to: localhost

- name: create backend deploy directory
  become: true
  file:
    path: "{{ deploy_path }}/ui/backend"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: upload ptinsight-ui
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_path }}/ui/backend"
  with_fileglob:
    - "{{ source_path }}/backend/dist/ptinsight_ui-*.whl"
  register: python_ui
  notify:
    - restart UI service

- name: remove virtual environment
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ui/backend/venv"
    state: absent

- name: install packages into new virtual environment
  become: true
  become_user: "{{ deploy_user }}"
  pip: 
    name: "file://{{ item.dest }}"
    virtualenv: "{{ deploy_path }}/ui/backend/venv"
    virtualenv_command: /usr/local/bin/python3 -m venv
  with_list: "{{ python_common.results + python_ui.results }}"

- name: create config directory
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ui/backend/config"
    state: directory

- name: upload config
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: ui.yaml.j2
    dest: "{{ deploy_path }}/ui/backend/config/ui.yaml"
  notify:
    - restart UI service

- name: upload start script
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: start.sh.j2
    dest: "{{ deploy_path }}/ui/backend/start.sh"
    mode: a+x

- name: Copy UI service file
  become: true
  template:
    src: ptinsight-ui.service.j2
    dest: /usr/lib/systemd/system/ptinsight-ui.service

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- meta: flush_handlers

- name: start the UI service
  become: true
  service:
    name: ptinsight-ui
    state: started
    enabled: yes
