// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptinsight/common/proto/egress/counts.proto

package com.dxc.ptinsight.proto.egress;

public final class Counts {
  private Counts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ArrivalCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.egress.ArrivalCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The enum numeric value on the wire for vehicleType.
     */
    int getVehicleTypeValue();
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The vehicleType.
     */
    com.dxc.ptinsight.proto.Base.VehicleType getVehicleType();

    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return Whether the windowStart field is set.
     */
    boolean hasWindowStart();
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return The windowStart.
     */
    com.google.protobuf.Timestamp getWindowStart();
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return Whether the windowEnd field is set.
     */
    boolean hasWindowEnd();
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return The windowEnd.
     */
    com.google.protobuf.Timestamp getWindowEnd();
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder();

    /**
     * <code>int32 count = 4;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.egress.ArrivalCount}
   */
  public static final class ArrivalCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.egress.ArrivalCount)
      ArrivalCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ArrivalCount.newBuilder() to construct.
    private ArrivalCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ArrivalCount() {
      vehicleType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ArrivalCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ArrivalCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              vehicleType_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (windowStart_ != null) {
                subBuilder = windowStart_.toBuilder();
              }
              windowStart_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(windowStart_);
                windowStart_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (windowEnd_ != null) {
                subBuilder = windowEnd_.toBuilder();
              }
              windowEnd_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(windowEnd_);
                windowEnd_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_ArrivalCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.class, com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.Builder.class);
    }

    public static final int VEHICLE_TYPE_FIELD_NUMBER = 1;
    private int vehicleType_;
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The enum numeric value on the wire for vehicleType.
     */
    @java.lang.Override public int getVehicleTypeValue() {
      return vehicleType_;
    }
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The vehicleType.
     */
    @java.lang.Override public com.dxc.ptinsight.proto.Base.VehicleType getVehicleType() {
      @SuppressWarnings("deprecation")
      com.dxc.ptinsight.proto.Base.VehicleType result = com.dxc.ptinsight.proto.Base.VehicleType.valueOf(vehicleType_);
      return result == null ? com.dxc.ptinsight.proto.Base.VehicleType.UNRECOGNIZED : result;
    }

    public static final int WINDOW_START_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp windowStart_;
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return Whether the windowStart field is set.
     */
    @java.lang.Override
    public boolean hasWindowStart() {
      return windowStart_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return The windowStart.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWindowStart() {
      return windowStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
    }
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder() {
      return getWindowStart();
    }

    public static final int WINDOW_END_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp windowEnd_;
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return Whether the windowEnd field is set.
     */
    @java.lang.Override
    public boolean hasWindowEnd() {
      return windowEnd_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return The windowEnd.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWindowEnd() {
      return windowEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
    }
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder() {
      return getWindowEnd();
    }

    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    /**
     * <code>int32 count = 4;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vehicleType_ != com.dxc.ptinsight.proto.Base.VehicleType.BUS.getNumber()) {
        output.writeEnum(1, vehicleType_);
      }
      if (windowStart_ != null) {
        output.writeMessage(2, getWindowStart());
      }
      if (windowEnd_ != null) {
        output.writeMessage(3, getWindowEnd());
      }
      if (count_ != 0) {
        output.writeInt32(4, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vehicleType_ != com.dxc.ptinsight.proto.Base.VehicleType.BUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, vehicleType_);
      }
      if (windowStart_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWindowStart());
      }
      if (windowEnd_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWindowEnd());
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.egress.Counts.ArrivalCount)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.egress.Counts.ArrivalCount other = (com.dxc.ptinsight.proto.egress.Counts.ArrivalCount) obj;

      if (vehicleType_ != other.vehicleType_) return false;
      if (hasWindowStart() != other.hasWindowStart()) return false;
      if (hasWindowStart()) {
        if (!getWindowStart()
            .equals(other.getWindowStart())) return false;
      }
      if (hasWindowEnd() != other.hasWindowEnd()) return false;
      if (hasWindowEnd()) {
        if (!getWindowEnd()
            .equals(other.getWindowEnd())) return false;
      }
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICLE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + vehicleType_;
      if (hasWindowStart()) {
        hash = (37 * hash) + WINDOW_START_FIELD_NUMBER;
        hash = (53 * hash) + getWindowStart().hashCode();
      }
      if (hasWindowEnd()) {
        hash = (37 * hash) + WINDOW_END_FIELD_NUMBER;
        hash = (53 * hash) + getWindowEnd().hashCode();
      }
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.egress.Counts.ArrivalCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.egress.ArrivalCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.egress.ArrivalCount)
        com.dxc.ptinsight.proto.egress.Counts.ArrivalCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_ArrivalCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.class, com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vehicleType_ = 0;

        if (windowStartBuilder_ == null) {
          windowStart_ = null;
        } else {
          windowStart_ = null;
          windowStartBuilder_ = null;
        }
        if (windowEndBuilder_ == null) {
          windowEnd_ = null;
        } else {
          windowEnd_ = null;
          windowEndBuilder_ = null;
        }
        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.ArrivalCount getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.ArrivalCount build() {
        com.dxc.ptinsight.proto.egress.Counts.ArrivalCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.ArrivalCount buildPartial() {
        com.dxc.ptinsight.proto.egress.Counts.ArrivalCount result = new com.dxc.ptinsight.proto.egress.Counts.ArrivalCount(this);
        result.vehicleType_ = vehicleType_;
        if (windowStartBuilder_ == null) {
          result.windowStart_ = windowStart_;
        } else {
          result.windowStart_ = windowStartBuilder_.build();
        }
        if (windowEndBuilder_ == null) {
          result.windowEnd_ = windowEnd_;
        } else {
          result.windowEnd_ = windowEndBuilder_.build();
        }
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.egress.Counts.ArrivalCount) {
          return mergeFrom((com.dxc.ptinsight.proto.egress.Counts.ArrivalCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.egress.Counts.ArrivalCount other) {
        if (other == com.dxc.ptinsight.proto.egress.Counts.ArrivalCount.getDefaultInstance()) return this;
        if (other.vehicleType_ != 0) {
          setVehicleTypeValue(other.getVehicleTypeValue());
        }
        if (other.hasWindowStart()) {
          mergeWindowStart(other.getWindowStart());
        }
        if (other.hasWindowEnd()) {
          mergeWindowEnd(other.getWindowEnd());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.egress.Counts.ArrivalCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.egress.Counts.ArrivalCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int vehicleType_ = 0;
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return The enum numeric value on the wire for vehicleType.
       */
      @java.lang.Override public int getVehicleTypeValue() {
        return vehicleType_;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @param value The enum numeric value on the wire for vehicleType to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleTypeValue(int value) {
        
        vehicleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return The vehicleType.
       */
      @java.lang.Override
      public com.dxc.ptinsight.proto.Base.VehicleType getVehicleType() {
        @SuppressWarnings("deprecation")
        com.dxc.ptinsight.proto.Base.VehicleType result = com.dxc.ptinsight.proto.Base.VehicleType.valueOf(vehicleType_);
        return result == null ? com.dxc.ptinsight.proto.Base.VehicleType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @param value The vehicleType to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleType(com.dxc.ptinsight.proto.Base.VehicleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        vehicleType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleType() {
        
        vehicleType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp windowStart_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> windowStartBuilder_;
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       * @return Whether the windowStart field is set.
       */
      public boolean hasWindowStart() {
        return windowStartBuilder_ != null || windowStart_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       * @return The windowStart.
       */
      public com.google.protobuf.Timestamp getWindowStart() {
        if (windowStartBuilder_ == null) {
          return windowStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
        } else {
          return windowStartBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder setWindowStart(com.google.protobuf.Timestamp value) {
        if (windowStartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          windowStart_ = value;
          onChanged();
        } else {
          windowStartBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder setWindowStart(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (windowStartBuilder_ == null) {
          windowStart_ = builderForValue.build();
          onChanged();
        } else {
          windowStartBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder mergeWindowStart(com.google.protobuf.Timestamp value) {
        if (windowStartBuilder_ == null) {
          if (windowStart_ != null) {
            windowStart_ =
              com.google.protobuf.Timestamp.newBuilder(windowStart_).mergeFrom(value).buildPartial();
          } else {
            windowStart_ = value;
          }
          onChanged();
        } else {
          windowStartBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder clearWindowStart() {
        if (windowStartBuilder_ == null) {
          windowStart_ = null;
          onChanged();
        } else {
          windowStart_ = null;
          windowStartBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWindowStartBuilder() {
        
        onChanged();
        return getWindowStartFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder() {
        if (windowStartBuilder_ != null) {
          return windowStartBuilder_.getMessageOrBuilder();
        } else {
          return windowStart_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWindowStartFieldBuilder() {
        if (windowStartBuilder_ == null) {
          windowStartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWindowStart(),
                  getParentForChildren(),
                  isClean());
          windowStart_ = null;
        }
        return windowStartBuilder_;
      }

      private com.google.protobuf.Timestamp windowEnd_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> windowEndBuilder_;
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       * @return Whether the windowEnd field is set.
       */
      public boolean hasWindowEnd() {
        return windowEndBuilder_ != null || windowEnd_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       * @return The windowEnd.
       */
      public com.google.protobuf.Timestamp getWindowEnd() {
        if (windowEndBuilder_ == null) {
          return windowEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
        } else {
          return windowEndBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder setWindowEnd(com.google.protobuf.Timestamp value) {
        if (windowEndBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          windowEnd_ = value;
          onChanged();
        } else {
          windowEndBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder setWindowEnd(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (windowEndBuilder_ == null) {
          windowEnd_ = builderForValue.build();
          onChanged();
        } else {
          windowEndBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder mergeWindowEnd(com.google.protobuf.Timestamp value) {
        if (windowEndBuilder_ == null) {
          if (windowEnd_ != null) {
            windowEnd_ =
              com.google.protobuf.Timestamp.newBuilder(windowEnd_).mergeFrom(value).buildPartial();
          } else {
            windowEnd_ = value;
          }
          onChanged();
        } else {
          windowEndBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder clearWindowEnd() {
        if (windowEndBuilder_ == null) {
          windowEnd_ = null;
          onChanged();
        } else {
          windowEnd_ = null;
          windowEndBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWindowEndBuilder() {
        
        onChanged();
        return getWindowEndFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder() {
        if (windowEndBuilder_ != null) {
          return windowEndBuilder_.getMessageOrBuilder();
        } else {
          return windowEnd_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWindowEndFieldBuilder() {
        if (windowEndBuilder_ == null) {
          windowEndBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWindowEnd(),
                  getParentForChildren(),
                  isClean());
          windowEnd_ = null;
        }
        return windowEndBuilder_;
      }

      private int count_ ;
      /**
       * <code>int32 count = 4;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 4;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.egress.ArrivalCount)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.ArrivalCount)
    private static final com.dxc.ptinsight.proto.egress.Counts.ArrivalCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.egress.Counts.ArrivalCount();
    }

    public static com.dxc.ptinsight.proto.egress.Counts.ArrivalCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ArrivalCount>
        PARSER = new com.google.protobuf.AbstractParser<ArrivalCount>() {
      @java.lang.Override
      public ArrivalCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ArrivalCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ArrivalCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ArrivalCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.egress.Counts.ArrivalCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DepartureCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.egress.DepartureCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The enum numeric value on the wire for vehicleType.
     */
    int getVehicleTypeValue();
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The vehicleType.
     */
    com.dxc.ptinsight.proto.Base.VehicleType getVehicleType();

    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return Whether the windowStart field is set.
     */
    boolean hasWindowStart();
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return The windowStart.
     */
    com.google.protobuf.Timestamp getWindowStart();
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return Whether the windowEnd field is set.
     */
    boolean hasWindowEnd();
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return The windowEnd.
     */
    com.google.protobuf.Timestamp getWindowEnd();
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     */
    com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder();

    /**
     * <code>int32 count = 4;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.egress.DepartureCount}
   */
  public static final class DepartureCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.egress.DepartureCount)
      DepartureCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DepartureCount.newBuilder() to construct.
    private DepartureCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DepartureCount() {
      vehicleType_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DepartureCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DepartureCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              vehicleType_ = rawValue;
              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (windowStart_ != null) {
                subBuilder = windowStart_.toBuilder();
              }
              windowStart_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(windowStart_);
                windowStart_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (windowEnd_ != null) {
                subBuilder = windowEnd_.toBuilder();
              }
              windowEnd_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(windowEnd_);
                windowEnd_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_DepartureCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.egress.Counts.DepartureCount.class, com.dxc.ptinsight.proto.egress.Counts.DepartureCount.Builder.class);
    }

    public static final int VEHICLE_TYPE_FIELD_NUMBER = 1;
    private int vehicleType_;
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The enum numeric value on the wire for vehicleType.
     */
    @java.lang.Override public int getVehicleTypeValue() {
      return vehicleType_;
    }
    /**
     * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
     * @return The vehicleType.
     */
    @java.lang.Override public com.dxc.ptinsight.proto.Base.VehicleType getVehicleType() {
      @SuppressWarnings("deprecation")
      com.dxc.ptinsight.proto.Base.VehicleType result = com.dxc.ptinsight.proto.Base.VehicleType.valueOf(vehicleType_);
      return result == null ? com.dxc.ptinsight.proto.Base.VehicleType.UNRECOGNIZED : result;
    }

    public static final int WINDOW_START_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp windowStart_;
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return Whether the windowStart field is set.
     */
    @java.lang.Override
    public boolean hasWindowStart() {
      return windowStart_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     * @return The windowStart.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWindowStart() {
      return windowStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
    }
    /**
     * <code>.google.protobuf.Timestamp window_start = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder() {
      return getWindowStart();
    }

    public static final int WINDOW_END_FIELD_NUMBER = 3;
    private com.google.protobuf.Timestamp windowEnd_;
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return Whether the windowEnd field is set.
     */
    @java.lang.Override
    public boolean hasWindowEnd() {
      return windowEnd_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     * @return The windowEnd.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getWindowEnd() {
      return windowEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
    }
    /**
     * <code>.google.protobuf.Timestamp window_end = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder() {
      return getWindowEnd();
    }

    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    /**
     * <code>int32 count = 4;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (vehicleType_ != com.dxc.ptinsight.proto.Base.VehicleType.BUS.getNumber()) {
        output.writeEnum(1, vehicleType_);
      }
      if (windowStart_ != null) {
        output.writeMessage(2, getWindowStart());
      }
      if (windowEnd_ != null) {
        output.writeMessage(3, getWindowEnd());
      }
      if (count_ != 0) {
        output.writeInt32(4, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (vehicleType_ != com.dxc.ptinsight.proto.Base.VehicleType.BUS.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, vehicleType_);
      }
      if (windowStart_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getWindowStart());
      }
      if (windowEnd_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWindowEnd());
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.egress.Counts.DepartureCount)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.egress.Counts.DepartureCount other = (com.dxc.ptinsight.proto.egress.Counts.DepartureCount) obj;

      if (vehicleType_ != other.vehicleType_) return false;
      if (hasWindowStart() != other.hasWindowStart()) return false;
      if (hasWindowStart()) {
        if (!getWindowStart()
            .equals(other.getWindowStart())) return false;
      }
      if (hasWindowEnd() != other.hasWindowEnd()) return false;
      if (hasWindowEnd()) {
        if (!getWindowEnd()
            .equals(other.getWindowEnd())) return false;
      }
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICLE_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + vehicleType_;
      if (hasWindowStart()) {
        hash = (37 * hash) + WINDOW_START_FIELD_NUMBER;
        hash = (53 * hash) + getWindowStart().hashCode();
      }
      if (hasWindowEnd()) {
        hash = (37 * hash) + WINDOW_END_FIELD_NUMBER;
        hash = (53 * hash) + getWindowEnd().hashCode();
      }
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.egress.Counts.DepartureCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.egress.DepartureCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.egress.DepartureCount)
        com.dxc.ptinsight.proto.egress.Counts.DepartureCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_DepartureCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.egress.Counts.DepartureCount.class, com.dxc.ptinsight.proto.egress.Counts.DepartureCount.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.egress.Counts.DepartureCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vehicleType_ = 0;

        if (windowStartBuilder_ == null) {
          windowStart_ = null;
        } else {
          windowStart_ = null;
          windowStartBuilder_ = null;
        }
        if (windowEndBuilder_ == null) {
          windowEnd_ = null;
        } else {
          windowEnd_ = null;
          windowEndBuilder_ = null;
        }
        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.DepartureCount getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.egress.Counts.DepartureCount.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.DepartureCount build() {
        com.dxc.ptinsight.proto.egress.Counts.DepartureCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.DepartureCount buildPartial() {
        com.dxc.ptinsight.proto.egress.Counts.DepartureCount result = new com.dxc.ptinsight.proto.egress.Counts.DepartureCount(this);
        result.vehicleType_ = vehicleType_;
        if (windowStartBuilder_ == null) {
          result.windowStart_ = windowStart_;
        } else {
          result.windowStart_ = windowStartBuilder_.build();
        }
        if (windowEndBuilder_ == null) {
          result.windowEnd_ = windowEnd_;
        } else {
          result.windowEnd_ = windowEndBuilder_.build();
        }
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.egress.Counts.DepartureCount) {
          return mergeFrom((com.dxc.ptinsight.proto.egress.Counts.DepartureCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.egress.Counts.DepartureCount other) {
        if (other == com.dxc.ptinsight.proto.egress.Counts.DepartureCount.getDefaultInstance()) return this;
        if (other.vehicleType_ != 0) {
          setVehicleTypeValue(other.getVehicleTypeValue());
        }
        if (other.hasWindowStart()) {
          mergeWindowStart(other.getWindowStart());
        }
        if (other.hasWindowEnd()) {
          mergeWindowEnd(other.getWindowEnd());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.egress.Counts.DepartureCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.egress.Counts.DepartureCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int vehicleType_ = 0;
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return The enum numeric value on the wire for vehicleType.
       */
      @java.lang.Override public int getVehicleTypeValue() {
        return vehicleType_;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @param value The enum numeric value on the wire for vehicleType to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleTypeValue(int value) {
        
        vehicleType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return The vehicleType.
       */
      @java.lang.Override
      public com.dxc.ptinsight.proto.Base.VehicleType getVehicleType() {
        @SuppressWarnings("deprecation")
        com.dxc.ptinsight.proto.Base.VehicleType result = com.dxc.ptinsight.proto.Base.VehicleType.valueOf(vehicleType_);
        return result == null ? com.dxc.ptinsight.proto.Base.VehicleType.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @param value The vehicleType to set.
       * @return This builder for chaining.
       */
      public Builder setVehicleType(com.dxc.ptinsight.proto.Base.VehicleType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        vehicleType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.dxc.ptinsight.VehicleType vehicle_type = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehicleType() {
        
        vehicleType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp windowStart_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> windowStartBuilder_;
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       * @return Whether the windowStart field is set.
       */
      public boolean hasWindowStart() {
        return windowStartBuilder_ != null || windowStart_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       * @return The windowStart.
       */
      public com.google.protobuf.Timestamp getWindowStart() {
        if (windowStartBuilder_ == null) {
          return windowStart_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
        } else {
          return windowStartBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder setWindowStart(com.google.protobuf.Timestamp value) {
        if (windowStartBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          windowStart_ = value;
          onChanged();
        } else {
          windowStartBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder setWindowStart(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (windowStartBuilder_ == null) {
          windowStart_ = builderForValue.build();
          onChanged();
        } else {
          windowStartBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder mergeWindowStart(com.google.protobuf.Timestamp value) {
        if (windowStartBuilder_ == null) {
          if (windowStart_ != null) {
            windowStart_ =
              com.google.protobuf.Timestamp.newBuilder(windowStart_).mergeFrom(value).buildPartial();
          } else {
            windowStart_ = value;
          }
          onChanged();
        } else {
          windowStartBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public Builder clearWindowStart() {
        if (windowStartBuilder_ == null) {
          windowStart_ = null;
          onChanged();
        } else {
          windowStart_ = null;
          windowStartBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWindowStartBuilder() {
        
        onChanged();
        return getWindowStartFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWindowStartOrBuilder() {
        if (windowStartBuilder_ != null) {
          return windowStartBuilder_.getMessageOrBuilder();
        } else {
          return windowStart_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : windowStart_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_start = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWindowStartFieldBuilder() {
        if (windowStartBuilder_ == null) {
          windowStartBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWindowStart(),
                  getParentForChildren(),
                  isClean());
          windowStart_ = null;
        }
        return windowStartBuilder_;
      }

      private com.google.protobuf.Timestamp windowEnd_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> windowEndBuilder_;
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       * @return Whether the windowEnd field is set.
       */
      public boolean hasWindowEnd() {
        return windowEndBuilder_ != null || windowEnd_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       * @return The windowEnd.
       */
      public com.google.protobuf.Timestamp getWindowEnd() {
        if (windowEndBuilder_ == null) {
          return windowEnd_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
        } else {
          return windowEndBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder setWindowEnd(com.google.protobuf.Timestamp value) {
        if (windowEndBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          windowEnd_ = value;
          onChanged();
        } else {
          windowEndBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder setWindowEnd(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (windowEndBuilder_ == null) {
          windowEnd_ = builderForValue.build();
          onChanged();
        } else {
          windowEndBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder mergeWindowEnd(com.google.protobuf.Timestamp value) {
        if (windowEndBuilder_ == null) {
          if (windowEnd_ != null) {
            windowEnd_ =
              com.google.protobuf.Timestamp.newBuilder(windowEnd_).mergeFrom(value).buildPartial();
          } else {
            windowEnd_ = value;
          }
          onChanged();
        } else {
          windowEndBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public Builder clearWindowEnd() {
        if (windowEndBuilder_ == null) {
          windowEnd_ = null;
          onChanged();
        } else {
          windowEnd_ = null;
          windowEndBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public com.google.protobuf.Timestamp.Builder getWindowEndBuilder() {
        
        onChanged();
        return getWindowEndFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getWindowEndOrBuilder() {
        if (windowEndBuilder_ != null) {
          return windowEndBuilder_.getMessageOrBuilder();
        } else {
          return windowEnd_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : windowEnd_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp window_end = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getWindowEndFieldBuilder() {
        if (windowEndBuilder_ == null) {
          windowEndBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getWindowEnd(),
                  getParentForChildren(),
                  isClean());
          windowEnd_ = null;
        }
        return windowEndBuilder_;
      }

      private int count_ ;
      /**
       * <code>int32 count = 4;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 4;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.egress.DepartureCount)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.DepartureCount)
    private static final com.dxc.ptinsight.proto.egress.Counts.DepartureCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.egress.Counts.DepartureCount();
    }

    public static com.dxc.ptinsight.proto.egress.Counts.DepartureCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DepartureCount>
        PARSER = new com.google.protobuf.AbstractParser<DepartureCount>() {
      @java.lang.Override
      public DepartureCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DepartureCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DepartureCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DepartureCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.egress.Counts.DepartureCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VehicleCountOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.egress.VehicleCount)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 geocell = 1;</code>
     * @return The geocell.
     */
    long getGeocell();

    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.egress.VehicleCount}
   */
  public static final class VehicleCount extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.egress.VehicleCount)
      VehicleCountOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use VehicleCount.newBuilder() to construct.
    private VehicleCount(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VehicleCount() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new VehicleCount();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private VehicleCount(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              geocell_ = input.readInt64();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_VehicleCount_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.egress.Counts.VehicleCount.class, com.dxc.ptinsight.proto.egress.Counts.VehicleCount.Builder.class);
    }

    public static final int GEOCELL_FIELD_NUMBER = 1;
    private long geocell_;
    /**
     * <code>int64 geocell = 1;</code>
     * @return The geocell.
     */
    @java.lang.Override
    public long getGeocell() {
      return geocell_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (geocell_ != 0L) {
        output.writeInt64(1, geocell_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (geocell_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, geocell_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.egress.Counts.VehicleCount)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.egress.Counts.VehicleCount other = (com.dxc.ptinsight.proto.egress.Counts.VehicleCount) obj;

      if (getGeocell()
          != other.getGeocell()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GEOCELL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGeocell());
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.egress.Counts.VehicleCount prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.egress.VehicleCount}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.egress.VehicleCount)
        com.dxc.ptinsight.proto.egress.Counts.VehicleCountOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_VehicleCount_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.egress.Counts.VehicleCount.class, com.dxc.ptinsight.proto.egress.Counts.VehicleCount.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.egress.Counts.VehicleCount.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        geocell_ = 0L;

        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.egress.Counts.internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.VehicleCount getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.egress.Counts.VehicleCount.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.VehicleCount build() {
        com.dxc.ptinsight.proto.egress.Counts.VehicleCount result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Counts.VehicleCount buildPartial() {
        com.dxc.ptinsight.proto.egress.Counts.VehicleCount result = new com.dxc.ptinsight.proto.egress.Counts.VehicleCount(this);
        result.geocell_ = geocell_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.egress.Counts.VehicleCount) {
          return mergeFrom((com.dxc.ptinsight.proto.egress.Counts.VehicleCount)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.egress.Counts.VehicleCount other) {
        if (other == com.dxc.ptinsight.proto.egress.Counts.VehicleCount.getDefaultInstance()) return this;
        if (other.getGeocell() != 0L) {
          setGeocell(other.getGeocell());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.egress.Counts.VehicleCount parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.egress.Counts.VehicleCount) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long geocell_ ;
      /**
       * <code>int64 geocell = 1;</code>
       * @return The geocell.
       */
      @java.lang.Override
      public long getGeocell() {
        return geocell_;
      }
      /**
       * <code>int64 geocell = 1;</code>
       * @param value The geocell to set.
       * @return This builder for chaining.
       */
      public Builder setGeocell(long value) {
        
        geocell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 geocell = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeocell() {
        
        geocell_ = 0L;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.egress.VehicleCount)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.VehicleCount)
    private static final com.dxc.ptinsight.proto.egress.Counts.VehicleCount DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.egress.Counts.VehicleCount();
    }

    public static com.dxc.ptinsight.proto.egress.Counts.VehicleCount getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VehicleCount>
        PARSER = new com.google.protobuf.AbstractParser<VehicleCount>() {
      @java.lang.Override
      public VehicleCount parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new VehicleCount(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VehicleCount> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VehicleCount> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.egress.Counts.VehicleCount getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_egress_ArrivalCount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_egress_DepartureCount_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_egress_VehicleCount_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*ptinsight/common/proto/egress/counts.p" +
      "roto\022\030com.dxc.ptinsight.egress\032!ptinsigh" +
      "t/common/proto/base.proto\032\037google/protob" +
      "uf/timestamp.proto\"\265\001\n\014ArrivalCount\0224\n\014v" +
      "ehicle_type\030\001 \001(\0162\036.com.dxc.ptinsight.Ve" +
      "hicleType\0220\n\014window_start\030\002 \001(\0132\032.google" +
      ".protobuf.Timestamp\022.\n\nwindow_end\030\003 \001(\0132" +
      "\032.google.protobuf.Timestamp\022\r\n\005count\030\004 \001" +
      "(\005\"\267\001\n\016DepartureCount\0224\n\014vehicle_type\030\001 " +
      "\001(\0162\036.com.dxc.ptinsight.VehicleType\0220\n\014w" +
      "indow_start\030\002 \001(\0132\032.google.protobuf.Time" +
      "stamp\022.\n\nwindow_end\030\003 \001(\0132\032.google.proto" +
      "buf.Timestamp\022\r\n\005count\030\004 \001(\005\".\n\014VehicleC" +
      "ount\022\017\n\007geocell\030\001 \001(\003\022\r\n\005count\030\002 \001(\005B \n\036" +
      "com.dxc.ptinsight.proto.egressb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.dxc.ptinsight.proto.Base.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dxc_ptinsight_egress_ArrivalCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_egress_ArrivalCount_descriptor,
        new java.lang.String[] { "VehicleType", "WindowStart", "WindowEnd", "Count", });
    internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_dxc_ptinsight_egress_DepartureCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_egress_DepartureCount_descriptor,
        new java.lang.String[] { "VehicleType", "WindowStart", "WindowEnd", "Count", });
    internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_dxc_ptinsight_egress_VehicleCount_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_egress_VehicleCount_descriptor,
        new java.lang.String[] { "Geocell", "Count", });
    com.dxc.ptinsight.proto.Base.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
