// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptinsight/common/proto/egress/delays.proto

package com.dxc.ptinsight.proto.egress;

public final class Delays {
  private Delays() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DelayStatisticsOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.egress.DelayStatistics)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 geocell = 1;</code>
     * @return The geocell.
     */
    long getGeocell();

    /**
     * <pre>
     * In seconds
     * </pre>
     *
     * <code>int64 percentile50th = 2;</code>
     * @return The percentile50th.
     */
    long getPercentile50Th();

    /**
     * <code>int64 percentile90th = 3;</code>
     * @return The percentile90th.
     */
    long getPercentile90Th();

    /**
     * <code>int64 percentile99th = 4;</code>
     * @return The percentile99th.
     */
    long getPercentile99Th();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.egress.DelayStatistics}
   */
  public static final class DelayStatistics extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.egress.DelayStatistics)
      DelayStatisticsOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DelayStatistics.newBuilder() to construct.
    private DelayStatistics(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DelayStatistics() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DelayStatistics();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DelayStatistics(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              geocell_ = input.readInt64();
              break;
            }
            case 16: {

              percentile50Th_ = input.readInt64();
              break;
            }
            case 24: {

              percentile90Th_ = input.readInt64();
              break;
            }
            case 32: {

              percentile99Th_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.egress.Delays.internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.egress.Delays.internal_static_com_dxc_ptinsight_egress_DelayStatistics_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.class, com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.Builder.class);
    }

    public static final int GEOCELL_FIELD_NUMBER = 1;
    private long geocell_;
    /**
     * <code>int64 geocell = 1;</code>
     * @return The geocell.
     */
    @java.lang.Override
    public long getGeocell() {
      return geocell_;
    }

    public static final int PERCENTILE50TH_FIELD_NUMBER = 2;
    private long percentile50Th_;
    /**
     * <pre>
     * In seconds
     * </pre>
     *
     * <code>int64 percentile50th = 2;</code>
     * @return The percentile50th.
     */
    @java.lang.Override
    public long getPercentile50Th() {
      return percentile50Th_;
    }

    public static final int PERCENTILE90TH_FIELD_NUMBER = 3;
    private long percentile90Th_;
    /**
     * <code>int64 percentile90th = 3;</code>
     * @return The percentile90th.
     */
    @java.lang.Override
    public long getPercentile90Th() {
      return percentile90Th_;
    }

    public static final int PERCENTILE99TH_FIELD_NUMBER = 4;
    private long percentile99Th_;
    /**
     * <code>int64 percentile99th = 4;</code>
     * @return The percentile99th.
     */
    @java.lang.Override
    public long getPercentile99Th() {
      return percentile99Th_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (geocell_ != 0L) {
        output.writeInt64(1, geocell_);
      }
      if (percentile50Th_ != 0L) {
        output.writeInt64(2, percentile50Th_);
      }
      if (percentile90Th_ != 0L) {
        output.writeInt64(3, percentile90Th_);
      }
      if (percentile99Th_ != 0L) {
        output.writeInt64(4, percentile99Th_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (geocell_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, geocell_);
      }
      if (percentile50Th_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, percentile50Th_);
      }
      if (percentile90Th_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, percentile90Th_);
      }
      if (percentile99Th_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, percentile99Th_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.egress.Delays.DelayStatistics)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.egress.Delays.DelayStatistics other = (com.dxc.ptinsight.proto.egress.Delays.DelayStatistics) obj;

      if (getGeocell()
          != other.getGeocell()) return false;
      if (getPercentile50Th()
          != other.getPercentile50Th()) return false;
      if (getPercentile90Th()
          != other.getPercentile90Th()) return false;
      if (getPercentile99Th()
          != other.getPercentile99Th()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GEOCELL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGeocell());
      hash = (37 * hash) + PERCENTILE50TH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPercentile50Th());
      hash = (37 * hash) + PERCENTILE90TH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPercentile90Th());
      hash = (37 * hash) + PERCENTILE99TH_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getPercentile99Th());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.egress.Delays.DelayStatistics prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.egress.DelayStatistics}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.egress.DelayStatistics)
        com.dxc.ptinsight.proto.egress.Delays.DelayStatisticsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.egress.Delays.internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.egress.Delays.internal_static_com_dxc_ptinsight_egress_DelayStatistics_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.class, com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        geocell_ = 0L;

        percentile50Th_ = 0L;

        percentile90Th_ = 0L;

        percentile99Th_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.egress.Delays.internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Delays.DelayStatistics getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Delays.DelayStatistics build() {
        com.dxc.ptinsight.proto.egress.Delays.DelayStatistics result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Delays.DelayStatistics buildPartial() {
        com.dxc.ptinsight.proto.egress.Delays.DelayStatistics result = new com.dxc.ptinsight.proto.egress.Delays.DelayStatistics(this);
        result.geocell_ = geocell_;
        result.percentile50Th_ = percentile50Th_;
        result.percentile90Th_ = percentile90Th_;
        result.percentile99Th_ = percentile99Th_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.egress.Delays.DelayStatistics) {
          return mergeFrom((com.dxc.ptinsight.proto.egress.Delays.DelayStatistics)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.egress.Delays.DelayStatistics other) {
        if (other == com.dxc.ptinsight.proto.egress.Delays.DelayStatistics.getDefaultInstance()) return this;
        if (other.getGeocell() != 0L) {
          setGeocell(other.getGeocell());
        }
        if (other.getPercentile50Th() != 0L) {
          setPercentile50Th(other.getPercentile50Th());
        }
        if (other.getPercentile90Th() != 0L) {
          setPercentile90Th(other.getPercentile90Th());
        }
        if (other.getPercentile99Th() != 0L) {
          setPercentile99Th(other.getPercentile99Th());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.egress.Delays.DelayStatistics parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.egress.Delays.DelayStatistics) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long geocell_ ;
      /**
       * <code>int64 geocell = 1;</code>
       * @return The geocell.
       */
      @java.lang.Override
      public long getGeocell() {
        return geocell_;
      }
      /**
       * <code>int64 geocell = 1;</code>
       * @param value The geocell to set.
       * @return This builder for chaining.
       */
      public Builder setGeocell(long value) {
        
        geocell_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 geocell = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeocell() {
        
        geocell_ = 0L;
        onChanged();
        return this;
      }

      private long percentile50Th_ ;
      /**
       * <pre>
       * In seconds
       * </pre>
       *
       * <code>int64 percentile50th = 2;</code>
       * @return The percentile50th.
       */
      @java.lang.Override
      public long getPercentile50Th() {
        return percentile50Th_;
      }
      /**
       * <pre>
       * In seconds
       * </pre>
       *
       * <code>int64 percentile50th = 2;</code>
       * @param value The percentile50th to set.
       * @return This builder for chaining.
       */
      public Builder setPercentile50Th(long value) {
        
        percentile50Th_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * In seconds
       * </pre>
       *
       * <code>int64 percentile50th = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPercentile50Th() {
        
        percentile50Th_ = 0L;
        onChanged();
        return this;
      }

      private long percentile90Th_ ;
      /**
       * <code>int64 percentile90th = 3;</code>
       * @return The percentile90th.
       */
      @java.lang.Override
      public long getPercentile90Th() {
        return percentile90Th_;
      }
      /**
       * <code>int64 percentile90th = 3;</code>
       * @param value The percentile90th to set.
       * @return This builder for chaining.
       */
      public Builder setPercentile90Th(long value) {
        
        percentile90Th_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 percentile90th = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPercentile90Th() {
        
        percentile90Th_ = 0L;
        onChanged();
        return this;
      }

      private long percentile99Th_ ;
      /**
       * <code>int64 percentile99th = 4;</code>
       * @return The percentile99th.
       */
      @java.lang.Override
      public long getPercentile99Th() {
        return percentile99Th_;
      }
      /**
       * <code>int64 percentile99th = 4;</code>
       * @param value The percentile99th to set.
       * @return This builder for chaining.
       */
      public Builder setPercentile99Th(long value) {
        
        percentile99Th_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 percentile99th = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPercentile99Th() {
        
        percentile99Th_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.egress.DelayStatistics)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.DelayStatistics)
    private static final com.dxc.ptinsight.proto.egress.Delays.DelayStatistics DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.egress.Delays.DelayStatistics();
    }

    public static com.dxc.ptinsight.proto.egress.Delays.DelayStatistics getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DelayStatistics>
        PARSER = new com.google.protobuf.AbstractParser<DelayStatistics>() {
      @java.lang.Override
      public DelayStatistics parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DelayStatistics(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DelayStatistics> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DelayStatistics> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.egress.Delays.DelayStatistics getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_egress_DelayStatistics_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*ptinsight/common/proto/egress/delays.p" +
      "roto\022\030com.dxc.ptinsight.egress\"j\n\017DelayS" +
      "tatistics\022\017\n\007geocell\030\001 \001(\003\022\026\n\016percentile" +
      "50th\030\002 \001(\003\022\026\n\016percentile90th\030\003 \001(\003\022\026\n\016pe" +
      "rcentile99th\030\004 \001(\003B \n\036com.dxc.ptinsight." +
      "proto.egressb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dxc_ptinsight_egress_DelayStatistics_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_egress_DelayStatistics_descriptor,
        new java.lang.String[] { "Geocell", "Percentile50Th", "Percentile90Th", "Percentile99Th", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
