// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptinsight/common/proto/egress/flow.proto

package com.dxc.ptinsight.proto.egress;

public final class Flow {
  private Flow() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FlowDirectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.egress.FlowDirection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int64 geocells_edge = 1;</code>
     * @return The geocellsEdge.
     */
    long getGeocellsEdge();

    /**
     * <pre>
     * Number of vehicles that traversed the edge
     * </pre>
     *
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    int getCount();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.egress.FlowDirection}
   */
  public static final class FlowDirection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.egress.FlowDirection)
      FlowDirectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FlowDirection.newBuilder() to construct.
    private FlowDirection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FlowDirection() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new FlowDirection();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FlowDirection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              geocellsEdge_ = input.readInt64();
              break;
            }
            case 16: {

              count_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.egress.Flow.internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.egress.Flow.internal_static_com_dxc_ptinsight_egress_FlowDirection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.egress.Flow.FlowDirection.class, com.dxc.ptinsight.proto.egress.Flow.FlowDirection.Builder.class);
    }

    public static final int GEOCELLS_EDGE_FIELD_NUMBER = 1;
    private long geocellsEdge_;
    /**
     * <code>int64 geocells_edge = 1;</code>
     * @return The geocellsEdge.
     */
    @java.lang.Override
    public long getGeocellsEdge() {
      return geocellsEdge_;
    }

    public static final int COUNT_FIELD_NUMBER = 2;
    private int count_;
    /**
     * <pre>
     * Number of vehicles that traversed the edge
     * </pre>
     *
     * <code>int32 count = 2;</code>
     * @return The count.
     */
    @java.lang.Override
    public int getCount() {
      return count_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (geocellsEdge_ != 0L) {
        output.writeInt64(1, geocellsEdge_);
      }
      if (count_ != 0) {
        output.writeInt32(2, count_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (geocellsEdge_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, geocellsEdge_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, count_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.egress.Flow.FlowDirection)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.egress.Flow.FlowDirection other = (com.dxc.ptinsight.proto.egress.Flow.FlowDirection) obj;

      if (getGeocellsEdge()
          != other.getGeocellsEdge()) return false;
      if (getCount()
          != other.getCount()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + GEOCELLS_EDGE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getGeocellsEdge());
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.egress.Flow.FlowDirection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.egress.FlowDirection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.egress.FlowDirection)
        com.dxc.ptinsight.proto.egress.Flow.FlowDirectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.egress.Flow.internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.egress.Flow.internal_static_com_dxc_ptinsight_egress_FlowDirection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.egress.Flow.FlowDirection.class, com.dxc.ptinsight.proto.egress.Flow.FlowDirection.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.egress.Flow.FlowDirection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        geocellsEdge_ = 0L;

        count_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.egress.Flow.internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Flow.FlowDirection getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.egress.Flow.FlowDirection.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Flow.FlowDirection build() {
        com.dxc.ptinsight.proto.egress.Flow.FlowDirection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.egress.Flow.FlowDirection buildPartial() {
        com.dxc.ptinsight.proto.egress.Flow.FlowDirection result = new com.dxc.ptinsight.proto.egress.Flow.FlowDirection(this);
        result.geocellsEdge_ = geocellsEdge_;
        result.count_ = count_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.egress.Flow.FlowDirection) {
          return mergeFrom((com.dxc.ptinsight.proto.egress.Flow.FlowDirection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.egress.Flow.FlowDirection other) {
        if (other == com.dxc.ptinsight.proto.egress.Flow.FlowDirection.getDefaultInstance()) return this;
        if (other.getGeocellsEdge() != 0L) {
          setGeocellsEdge(other.getGeocellsEdge());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.egress.Flow.FlowDirection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.egress.Flow.FlowDirection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long geocellsEdge_ ;
      /**
       * <code>int64 geocells_edge = 1;</code>
       * @return The geocellsEdge.
       */
      @java.lang.Override
      public long getGeocellsEdge() {
        return geocellsEdge_;
      }
      /**
       * <code>int64 geocells_edge = 1;</code>
       * @param value The geocellsEdge to set.
       * @return This builder for chaining.
       */
      public Builder setGeocellsEdge(long value) {
        
        geocellsEdge_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 geocells_edge = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGeocellsEdge() {
        
        geocellsEdge_ = 0L;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <pre>
       * Number of vehicles that traversed the edge
       * </pre>
       *
       * <code>int32 count = 2;</code>
       * @return The count.
       */
      @java.lang.Override
      public int getCount() {
        return count_;
      }
      /**
       * <pre>
       * Number of vehicles that traversed the edge
       * </pre>
       *
       * <code>int32 count = 2;</code>
       * @param value The count to set.
       * @return This builder for chaining.
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Number of vehicles that traversed the edge
       * </pre>
       *
       * <code>int32 count = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.egress.FlowDirection)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.FlowDirection)
    private static final com.dxc.ptinsight.proto.egress.Flow.FlowDirection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.egress.Flow.FlowDirection();
    }

    public static com.dxc.ptinsight.proto.egress.Flow.FlowDirection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FlowDirection>
        PARSER = new com.google.protobuf.AbstractParser<FlowDirection>() {
      @java.lang.Override
      public FlowDirection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FlowDirection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FlowDirection> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FlowDirection> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.egress.Flow.FlowDirection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_egress_FlowDirection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n(ptinsight/common/proto/egress/flow.pro" +
      "to\022\030com.dxc.ptinsight.egress\"5\n\rFlowDire" +
      "ction\022\025\n\rgeocells_edge\030\001 \001(\003\022\r\n\005count\030\002 " +
      "\001(\005B \n\036com.dxc.ptinsight.proto.egressb\006p" +
      "roto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dxc_ptinsight_egress_FlowDirection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_egress_FlowDirection_descriptor,
        new java.lang.String[] { "GeocellsEdge", "Count", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
