---
- name: set up all hosts
  hosts: all
  roles:
    - { role: ../../ansible/roles/common,
        tags: setup }

- name: set up Kafka cluster
  hosts: kafka
  roles:
    - { role: ../ansible/roles/kafka,
        tags: setup }
    - { role: kafka-deploy,
        tags: deploy }

- name: set up Flink cluster
  hosts: flink
  vars:
    - source_path: "{{ playbook_dir }}/../processing"
    - deploy_path: /opt/ptinsight/processing
    - deploy_user: flink
  roles:
    - { role: ../ansible/roles/flink,
        tags: setup }
    - { role: flink-deploy,
        tags: deploy }

- name: set up Ingest cluster
  hosts: ingest
  vars:
    - source_path: "{{ playbook_dir }}/../ingest"
    - deploy_path: /opt/ptinsight
    - deploy_user: ptinsight
  roles:
    - { role: ../ansible/roles/python,
        tags: setup }
    - { role: ingest-deploy,
        tags: deploy }

- name: set up UI cluster
  hosts: ui
  vars:
    - source_path: "{{ playbook_dir }}/../ui"
    - deploy_path: /opt/ptinsight
    - deploy_user: ptinsight
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  roles:
    - { role: ../ansible/roles/python,
        tags: setup }
    - { role: ui-deploy,
        tags: deploy }
