---
- name: set up playbook variables
  hosts: all
  tags: always
  tasks:
    - name: get Kafka server addresses
      command:
        argv: 
          - "{{ playbook_dir }}/../../tools/terraform-inventory/terraform_inventory.py"
          - --list-private
        chdir: "{{ playbook_dir }}/.."
      delegate_to: localhost
      register: kafka_servers_result
    - name: set Kafka server addresses variable
      set_fact:
        kafka_servers: "{{ (kafka_servers_result.stdout | from_json).kafka | map('regex_replace', '$', ':9092') | list }}"

- name: set up all hosts
  hosts: all
  roles:
    - { role: ../../ansible/roles/common,
        tags: setup }

- name: set up Kafka cluster
  hosts: kafka
  roles:
    - { role: ../ansible/roles/kafka,
        tags: [setup, setup-kafka] }
    - { role: kafka-deploy,
        tags: [deploy, deploy-kafka] }

- name: set up processing cluster
  hosts: processing
  vars:
    - source_path: "{{ playbook_dir }}/../processing"
    - deploy_path: /opt/ptinsight/processing
    - deploy_user: flink
  roles:
    - { role: ../ansible/roles/flink,
        tags: [setup, setup-processing] }
    - { role: processing-deploy,
        tags: [deploy, deploy-processing] }

- name: set up Ingest cluster
  hosts: ingest
  vars:
    - source_path: "{{ playbook_dir }}/../ingest"
    - deploy_path: /opt/ptinsight
    - deploy_user: ptinsight
  roles:
    - { role: ../ansible/roles/python,
        tags: [setup, setup-ingest] }
    - { role: ingest-deploy,
        tags: [deploy, deploy-ingest] }

- name: set up UI cluster
  hosts: ui
  vars:
    - source_path: "{{ playbook_dir }}/../ui"
    - deploy_path: /opt/ptinsight
    - deploy_user: ptinsight
  environment:
    PATH: "{{ ansible_env.PATH }}:/usr/local/bin"
  roles:
    - { role: ../ansible/roles/python,
        tags: [setup, setup-ui] }
    - { role: ui-deploy,
        tags: [deploy, deploy-ui] }
