---
- name: create deploy directory
  become: true
  file:
    path: "{{ deploy_path }}/ingest"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: upload application
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ source_path }}/{{ item }}"
    dest: "{{ deploy_path }}/ingest"
  loop:
    - Pipfile
    - Pipfile.lock
    - ptinsight
  notify:
    - restart ingest service

- name: create config directory
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ingest/config"
    state: directory

- name: get Kafka server addresses
  command:
    argv: 
      - "{{ playbook_dir }}/../../tools/terraform-inventory/terraform_inventory.py"
      - --list-private
    chdir: "{{ playbook_dir }}/.."
  delegate_to: localhost
  register: kafka_bootstrap_servers

- name: upload config
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: ingest.yaml.j2
    dest: "{{ deploy_path }}/ingest/config/ingest.yaml"
  notify:
    - restart ingest service

- name: Copy ingest service file
  become: true
  template:
    src: ptinsight-ingest.service.j2
    dest: /usr/lib/systemd/system/ptinsight-ingest.service

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- name: install dependencies
  become: true
  become_user: "{{ deploy_user }}"
  command: 
    cmd: /usr/local/bin/pipenv sync --python /usr/local/bin/python3
    chdir: "{{ deploy_path }}/ingest"

- meta: flush_handlers

- name: start the ingest service
  become: true
  service:
    name: ptinsight-ingest
    state: started
    enabled: yes
