---
- name: create deploy directory
  become: true
  file:
    path: "{{ deploy_path }}/ingest"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: build ptinsight-ingest
  run_once: true
  command:
    cmd: poetry build --format=wheel
    chdir: "{{ source_path }}"
  delegate_to: localhost

- name: upload ptinsight-ingest
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_path }}/ingest"
  with_fileglob:
    - "{{ source_path }}/dist/ptinsight_ingest-*.whl"
  register: python_ingest
  notify:
    - restart ingest service

- name: remove virtual environment
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ingest/venv"
    state: absent

- name: install packages
  become: true
  become_user: "{{ deploy_user }}"
  pip: 
    name: "file://{{ item.dest }}"
    virtualenv: "{{ deploy_path }}/ingest/venv"
    virtualenv_command: /usr/local/bin/python3 -m venv
  with_list: "{{ python_common.results + python_ingest.results }}"

- name: create config directory
  become: true
  become_user: "{{ deploy_user }}"
  file:
    path: "{{ deploy_path }}/ingest/config"
    state: directory

- name: upload config
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: ingest.yaml.j2
    dest: "{{ deploy_path }}/ingest/config/ingest.yaml"
  notify:
    - restart ingest service

- name: upload start script
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: start.sh.j2
    dest: "{{ deploy_path }}/ingest/start.sh"
    mode: a+x

- name: upload ingest service file
  become: true
  template:
    src: ptinsight-ingest.service.j2
    dest: /usr/lib/systemd/system/ptinsight-ingest.service

- name: reload systemd
  become: true
  systemd:
    daemon_reload: yes

- meta: flush_handlers

- name: start the ingest service
  become: true
  service:
    name: ptinsight-ingest
    state: started
    enabled: yes
