---
- name: add epel-release package repo
  become: true
  package:
    name: epel-release
    state: present

- name: install common packages
  become: true
  package:
    name: htop, wget, zip, unzip, tmux, at, chrony, tree, nc
    state: present

- name: start at
  become: true
  systemd:
    state: started
    name: atd

- name: add Amazon Time Sync server
  become: true
  lineinfile:
    path: /etc/chrony.conf
    line: server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4
    insertbefore: BOF
  notify: restart chrony service

- name: check AWS CLI installation
  become: true
  command: /usr/local/bin/aws --version
  failed_when: no
  register: awscli_version

- name: install AWS CLI
  become: true
  block:
    - name: download and untar AWS CLI
      unarchive:
        src: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp
        remote_src: yes

    - name: install AWS CLI
      command: /tmp/aws/install

    - name: remove AWS CLI installation folder
      file:
        path: /tmp/aws
        state: absent
  when: >
    awscli_version.rc != 0 or not awscli_version.stdout is match('aws-cli')
