---
- name: install htop
  become: true
  package:
    name: htop
    state: present

- name: install wget
  become: true
  package:
    name: wget
    state: present

- name: install epel-release
  become: true
  package:
    name: epel-release
    state: present
