---
- name: build jobs
  run_once: true
  command:
    argv: 
      - ./gradlew
      - clean
      - shadowJar
    chdir: "{{ source_path }}"
  delegate_to: localhost

- name: create deploy directory
  become: true
  file:
    path: "{{ deploy_path }}"
    state: directory
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: upload jobs
  become: true
  become_user: "{{ deploy_user }}"
  copy:
    src: "{{ item }}"
    dest: "{{ deploy_path }}/{{ item | basename }}"
  with_fileglob:
    - "{{ source_path }}/build/libs/*.jar"
  register: uploaded_jars

- name: upload config
  become: true
  become_user: "{{ deploy_user }}"
  template:
    src: processing.yaml.j2
    dest: "/tmp/processing.yaml"

- name: copy configuration into job jars
  become: true
  become_user: "{{ deploy_user }}"
  command:
    cmd: "zip {{ item.dest }} processing.yaml"
    chdir: /tmp
  loop: "{{ uploaded_jars.results }}"

- name: start jobs
  become: true
  become_user: "{{ deploy_user }}"
  command: "/opt/flink/bin/flink run --detached {{ item.dest }}"
  loop: "{{ uploaded_jars.results }}"

