---
- name: add Kafka user
  become: true
  user:
    name: kafka

- name: check Kafka installation
  become: true
  command: /opt/kafka/bin/kafka-topics.sh --version
  failed_when: no
  register: kafka_version

- name: install Kafka as service
  become: true
  block:
    - name: find Kafka mirror
      uri:
        url: https://www.apache.org/dyn/closer.cgi?as_json
        return_content: yes
      register: kafka_mirror

    - name: download and untar Kafka
      unarchive:
        src: "{{ kafka_mirror.json.preferred }}/kafka/2.5.0/kafka_2.12-2.5.0.tgz"
        dest: /opt
        remote_src: yes

    - name: add generic Kafka symlink
      file:
        src: /opt/kafka_2.12-2.5.0
        dest: /opt/kafka
        state: link

    - name: set Kafka permissions
      file:
        path: /opt/kafka
        state: directory
        recurse: yes
        owner: kafka
        group: kafka

    - name: Copy Kafka service file
      template:
        src: kafka.service.j2
        dest: /usr/lib/systemd/system/kafka.service

    - name: reload systemd
      systemd:
          daemon_reload: yes
  when: >
    kafka_version.rc != 0 or not kafka_version.stdout is match('2.5.0')

- name: upload broker properties
  become: true
  template:
    src: server.properties.j2
    dest: '/opt/kafka/config/server.properties'
  notify:
    - restart Kafka service

- meta: flush_handlers

- name: start the Kafka service
  become: true
  service:
    name: kafka
    state: started
    enabled: yes
