// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ptinsight/common/proto/base.proto

package com.dxc.ptinsight.proto;

public final class Base {
  private Base() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.dxc.ptinsight.VehicleType}
   */
  public enum VehicleType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>BUS = 0;</code>
     */
    BUS(0),
    /**
     * <code>TRAM = 1;</code>
     */
    TRAM(1),
    /**
     * <code>TRAIN = 2;</code>
     */
    TRAIN(2),
    /**
     * <code>FERRY = 3;</code>
     */
    FERRY(3),
    /**
     * <code>METRO = 4;</code>
     */
    METRO(4),
    /**
     * <code>UBUS = 5;</code>
     */
    UBUS(5),
    /**
     * <code>ROBOT = 6;</code>
     */
    ROBOT(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>BUS = 0;</code>
     */
    public static final int BUS_VALUE = 0;
    /**
     * <code>TRAM = 1;</code>
     */
    public static final int TRAM_VALUE = 1;
    /**
     * <code>TRAIN = 2;</code>
     */
    public static final int TRAIN_VALUE = 2;
    /**
     * <code>FERRY = 3;</code>
     */
    public static final int FERRY_VALUE = 3;
    /**
     * <code>METRO = 4;</code>
     */
    public static final int METRO_VALUE = 4;
    /**
     * <code>UBUS = 5;</code>
     */
    public static final int UBUS_VALUE = 5;
    /**
     * <code>ROBOT = 6;</code>
     */
    public static final int ROBOT_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static VehicleType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static VehicleType forNumber(int value) {
      switch (value) {
        case 0: return BUS;
        case 1: return TRAM;
        case 2: return TRAIN;
        case 3: return FERRY;
        case 4: return METRO;
        case 5: return UBUS;
        case 6: return ROBOT;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<VehicleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        VehicleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<VehicleType>() {
            public VehicleType findValueByNumber(int number) {
              return VehicleType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.Base.getDescriptor().getEnumTypes().get(0);
    }

    private static final VehicleType[] VALUES = values();

    public static VehicleType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private VehicleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.dxc.ptinsight.VehicleType)
  }

  public interface EventOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.dxc.ptinsight.Event)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     * @return Whether the eventTimestamp field is set.
     */
    boolean hasEventTimestamp();
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     * @return The eventTimestamp.
     */
    com.google.protobuf.Timestamp getEventTimestamp();
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     */
    com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder();

    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     * @return Whether the ingestionTimestamp field is set.
     */
    boolean hasIngestionTimestamp();
    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     * @return The ingestionTimestamp.
     */
    com.google.protobuf.Timestamp getIngestionTimestamp();
    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     */
    com.google.protobuf.TimestampOrBuilder getIngestionTimestampOrBuilder();

    /**
     * <code>.google.protobuf.Any details = 3;</code>
     * @return Whether the details field is set.
     */
    boolean hasDetails();
    /**
     * <code>.google.protobuf.Any details = 3;</code>
     * @return The details.
     */
    com.google.protobuf.Any getDetails();
    /**
     * <code>.google.protobuf.Any details = 3;</code>
     */
    com.google.protobuf.AnyOrBuilder getDetailsOrBuilder();
  }
  /**
   * Protobuf type {@code com.dxc.ptinsight.Event}
   */
  public static final class Event extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.dxc.ptinsight.Event)
      EventOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Event.newBuilder() to construct.
    private Event(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Event() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Event();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Event(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (eventTimestamp_ != null) {
                subBuilder = eventTimestamp_.toBuilder();
              }
              eventTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(eventTimestamp_);
                eventTimestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (ingestionTimestamp_ != null) {
                subBuilder = ingestionTimestamp_.toBuilder();
              }
              ingestionTimestamp_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(ingestionTimestamp_);
                ingestionTimestamp_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.google.protobuf.Any.Builder subBuilder = null;
              if (details_ != null) {
                subBuilder = details_.toBuilder();
              }
              details_ = input.readMessage(com.google.protobuf.Any.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(details_);
                details_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.dxc.ptinsight.proto.Base.internal_static_com_dxc_ptinsight_Event_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.dxc.ptinsight.proto.Base.internal_static_com_dxc_ptinsight_Event_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.dxc.ptinsight.proto.Base.Event.class, com.dxc.ptinsight.proto.Base.Event.Builder.class);
    }

    public static final int EVENT_TIMESTAMP_FIELD_NUMBER = 1;
    private com.google.protobuf.Timestamp eventTimestamp_;
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     * @return Whether the eventTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasEventTimestamp() {
      return eventTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     * @return The eventTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getEventTimestamp() {
      return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
      return getEventTimestamp();
    }

    public static final int INGESTION_TIMESTAMP_FIELD_NUMBER = 2;
    private com.google.protobuf.Timestamp ingestionTimestamp_;
    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     * @return Whether the ingestionTimestamp field is set.
     */
    @java.lang.Override
    public boolean hasIngestionTimestamp() {
      return ingestionTimestamp_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     * @return The ingestionTimestamp.
     */
    @java.lang.Override
    public com.google.protobuf.Timestamp getIngestionTimestamp() {
      return ingestionTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : ingestionTimestamp_;
    }
    /**
     * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.TimestampOrBuilder getIngestionTimestampOrBuilder() {
      return getIngestionTimestamp();
    }

    public static final int DETAILS_FIELD_NUMBER = 3;
    private com.google.protobuf.Any details_;
    /**
     * <code>.google.protobuf.Any details = 3;</code>
     * @return Whether the details field is set.
     */
    @java.lang.Override
    public boolean hasDetails() {
      return details_ != null;
    }
    /**
     * <code>.google.protobuf.Any details = 3;</code>
     * @return The details.
     */
    @java.lang.Override
    public com.google.protobuf.Any getDetails() {
      return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
    }
    /**
     * <code>.google.protobuf.Any details = 3;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
      return getDetails();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (eventTimestamp_ != null) {
        output.writeMessage(1, getEventTimestamp());
      }
      if (ingestionTimestamp_ != null) {
        output.writeMessage(2, getIngestionTimestamp());
      }
      if (details_ != null) {
        output.writeMessage(3, getDetails());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (eventTimestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getEventTimestamp());
      }
      if (ingestionTimestamp_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getIngestionTimestamp());
      }
      if (details_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getDetails());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.dxc.ptinsight.proto.Base.Event)) {
        return super.equals(obj);
      }
      com.dxc.ptinsight.proto.Base.Event other = (com.dxc.ptinsight.proto.Base.Event) obj;

      if (hasEventTimestamp() != other.hasEventTimestamp()) return false;
      if (hasEventTimestamp()) {
        if (!getEventTimestamp()
            .equals(other.getEventTimestamp())) return false;
      }
      if (hasIngestionTimestamp() != other.hasIngestionTimestamp()) return false;
      if (hasIngestionTimestamp()) {
        if (!getIngestionTimestamp()
            .equals(other.getIngestionTimestamp())) return false;
      }
      if (hasDetails() != other.hasDetails()) return false;
      if (hasDetails()) {
        if (!getDetails()
            .equals(other.getDetails())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasEventTimestamp()) {
        hash = (37 * hash) + EVENT_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getEventTimestamp().hashCode();
      }
      if (hasIngestionTimestamp()) {
        hash = (37 * hash) + INGESTION_TIMESTAMP_FIELD_NUMBER;
        hash = (53 * hash) + getIngestionTimestamp().hashCode();
      }
      if (hasDetails()) {
        hash = (37 * hash) + DETAILS_FIELD_NUMBER;
        hash = (53 * hash) + getDetails().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.dxc.ptinsight.proto.Base.Event parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.dxc.ptinsight.proto.Base.Event prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.dxc.ptinsight.Event}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.dxc.ptinsight.Event)
        com.dxc.ptinsight.proto.Base.EventOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.dxc.ptinsight.proto.Base.internal_static_com_dxc_ptinsight_Event_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.dxc.ptinsight.proto.Base.internal_static_com_dxc_ptinsight_Event_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.dxc.ptinsight.proto.Base.Event.class, com.dxc.ptinsight.proto.Base.Event.Builder.class);
      }

      // Construct using com.dxc.ptinsight.proto.Base.Event.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = null;
        } else {
          eventTimestamp_ = null;
          eventTimestampBuilder_ = null;
        }
        if (ingestionTimestampBuilder_ == null) {
          ingestionTimestamp_ = null;
        } else {
          ingestionTimestamp_ = null;
          ingestionTimestampBuilder_ = null;
        }
        if (detailsBuilder_ == null) {
          details_ = null;
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.dxc.ptinsight.proto.Base.internal_static_com_dxc_ptinsight_Event_descriptor;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.Base.Event getDefaultInstanceForType() {
        return com.dxc.ptinsight.proto.Base.Event.getDefaultInstance();
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.Base.Event build() {
        com.dxc.ptinsight.proto.Base.Event result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.dxc.ptinsight.proto.Base.Event buildPartial() {
        com.dxc.ptinsight.proto.Base.Event result = new com.dxc.ptinsight.proto.Base.Event(this);
        if (eventTimestampBuilder_ == null) {
          result.eventTimestamp_ = eventTimestamp_;
        } else {
          result.eventTimestamp_ = eventTimestampBuilder_.build();
        }
        if (ingestionTimestampBuilder_ == null) {
          result.ingestionTimestamp_ = ingestionTimestamp_;
        } else {
          result.ingestionTimestamp_ = ingestionTimestampBuilder_.build();
        }
        if (detailsBuilder_ == null) {
          result.details_ = details_;
        } else {
          result.details_ = detailsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.dxc.ptinsight.proto.Base.Event) {
          return mergeFrom((com.dxc.ptinsight.proto.Base.Event)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.dxc.ptinsight.proto.Base.Event other) {
        if (other == com.dxc.ptinsight.proto.Base.Event.getDefaultInstance()) return this;
        if (other.hasEventTimestamp()) {
          mergeEventTimestamp(other.getEventTimestamp());
        }
        if (other.hasIngestionTimestamp()) {
          mergeIngestionTimestamp(other.getIngestionTimestamp());
        }
        if (other.hasDetails()) {
          mergeDetails(other.getDetails());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.dxc.ptinsight.proto.Base.Event parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.dxc.ptinsight.proto.Base.Event) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.Timestamp eventTimestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> eventTimestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       * @return Whether the eventTimestamp field is set.
       */
      public boolean hasEventTimestamp() {
        return eventTimestampBuilder_ != null || eventTimestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       * @return The eventTimestamp.
       */
      public com.google.protobuf.Timestamp getEventTimestamp() {
        if (eventTimestampBuilder_ == null) {
          return eventTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
        } else {
          return eventTimestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public Builder setEventTimestamp(com.google.protobuf.Timestamp value) {
        if (eventTimestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          eventTimestamp_ = value;
          onChanged();
        } else {
          eventTimestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public Builder setEventTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = builderForValue.build();
          onChanged();
        } else {
          eventTimestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public Builder mergeEventTimestamp(com.google.protobuf.Timestamp value) {
        if (eventTimestampBuilder_ == null) {
          if (eventTimestamp_ != null) {
            eventTimestamp_ =
              com.google.protobuf.Timestamp.newBuilder(eventTimestamp_).mergeFrom(value).buildPartial();
          } else {
            eventTimestamp_ = value;
          }
          onChanged();
        } else {
          eventTimestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public Builder clearEventTimestamp() {
        if (eventTimestampBuilder_ == null) {
          eventTimestamp_ = null;
          onChanged();
        } else {
          eventTimestamp_ = null;
          eventTimestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public com.google.protobuf.Timestamp.Builder getEventTimestampBuilder() {
        
        onChanged();
        return getEventTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getEventTimestampOrBuilder() {
        if (eventTimestampBuilder_ != null) {
          return eventTimestampBuilder_.getMessageOrBuilder();
        } else {
          return eventTimestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : eventTimestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp event_timestamp = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getEventTimestampFieldBuilder() {
        if (eventTimestampBuilder_ == null) {
          eventTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getEventTimestamp(),
                  getParentForChildren(),
                  isClean());
          eventTimestamp_ = null;
        }
        return eventTimestampBuilder_;
      }

      private com.google.protobuf.Timestamp ingestionTimestamp_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> ingestionTimestampBuilder_;
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       * @return Whether the ingestionTimestamp field is set.
       */
      public boolean hasIngestionTimestamp() {
        return ingestionTimestampBuilder_ != null || ingestionTimestamp_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       * @return The ingestionTimestamp.
       */
      public com.google.protobuf.Timestamp getIngestionTimestamp() {
        if (ingestionTimestampBuilder_ == null) {
          return ingestionTimestamp_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : ingestionTimestamp_;
        } else {
          return ingestionTimestampBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public Builder setIngestionTimestamp(com.google.protobuf.Timestamp value) {
        if (ingestionTimestampBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ingestionTimestamp_ = value;
          onChanged();
        } else {
          ingestionTimestampBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public Builder setIngestionTimestamp(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (ingestionTimestampBuilder_ == null) {
          ingestionTimestamp_ = builderForValue.build();
          onChanged();
        } else {
          ingestionTimestampBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public Builder mergeIngestionTimestamp(com.google.protobuf.Timestamp value) {
        if (ingestionTimestampBuilder_ == null) {
          if (ingestionTimestamp_ != null) {
            ingestionTimestamp_ =
              com.google.protobuf.Timestamp.newBuilder(ingestionTimestamp_).mergeFrom(value).buildPartial();
          } else {
            ingestionTimestamp_ = value;
          }
          onChanged();
        } else {
          ingestionTimestampBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public Builder clearIngestionTimestamp() {
        if (ingestionTimestampBuilder_ == null) {
          ingestionTimestamp_ = null;
          onChanged();
        } else {
          ingestionTimestamp_ = null;
          ingestionTimestampBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public com.google.protobuf.Timestamp.Builder getIngestionTimestampBuilder() {
        
        onChanged();
        return getIngestionTimestampFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getIngestionTimestampOrBuilder() {
        if (ingestionTimestampBuilder_ != null) {
          return ingestionTimestampBuilder_.getMessageOrBuilder();
        } else {
          return ingestionTimestamp_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : ingestionTimestamp_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp ingestion_timestamp = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getIngestionTimestampFieldBuilder() {
        if (ingestionTimestampBuilder_ == null) {
          ingestionTimestampBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getIngestionTimestamp(),
                  getParentForChildren(),
                  isClean());
          ingestionTimestamp_ = null;
        }
        return ingestionTimestampBuilder_;
      }

      private com.google.protobuf.Any details_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> detailsBuilder_;
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       * @return Whether the details field is set.
       */
      public boolean hasDetails() {
        return detailsBuilder_ != null || details_ != null;
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       * @return The details.
       */
      public com.google.protobuf.Any getDetails() {
        if (detailsBuilder_ == null) {
          return details_ == null ? com.google.protobuf.Any.getDefaultInstance() : details_;
        } else {
          return detailsBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public Builder setDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          details_ = value;
          onChanged();
        } else {
          detailsBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public Builder setDetails(
          com.google.protobuf.Any.Builder builderForValue) {
        if (detailsBuilder_ == null) {
          details_ = builderForValue.build();
          onChanged();
        } else {
          detailsBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public Builder mergeDetails(com.google.protobuf.Any value) {
        if (detailsBuilder_ == null) {
          if (details_ != null) {
            details_ =
              com.google.protobuf.Any.newBuilder(details_).mergeFrom(value).buildPartial();
          } else {
            details_ = value;
          }
          onChanged();
        } else {
          detailsBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public Builder clearDetails() {
        if (detailsBuilder_ == null) {
          details_ = null;
          onChanged();
        } else {
          details_ = null;
          detailsBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public com.google.protobuf.Any.Builder getDetailsBuilder() {
        
        onChanged();
        return getDetailsFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      public com.google.protobuf.AnyOrBuilder getDetailsOrBuilder() {
        if (detailsBuilder_ != null) {
          return detailsBuilder_.getMessageOrBuilder();
        } else {
          return details_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : details_;
        }
      }
      /**
       * <code>.google.protobuf.Any details = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getDetailsFieldBuilder() {
        if (detailsBuilder_ == null) {
          detailsBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getDetails(),
                  getParentForChildren(),
                  isClean());
          details_ = null;
        }
        return detailsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.dxc.ptinsight.Event)
    }

    // @@protoc_insertion_point(class_scope:com.dxc.ptinsight.Event)
    private static final com.dxc.ptinsight.proto.Base.Event DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.dxc.ptinsight.proto.Base.Event();
    }

    public static com.dxc.ptinsight.proto.Base.Event getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Event>
        PARSER = new com.google.protobuf.AbstractParser<Event>() {
      @java.lang.Override
      public Event parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Event(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Event> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Event> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.dxc.ptinsight.proto.Base.Event getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_dxc_ptinsight_Event_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_dxc_ptinsight_Event_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!ptinsight/common/proto/base.proto\022\021com" +
      ".dxc.ptinsight\032\031google/protobuf/any.prot" +
      "o\032\037google/protobuf/timestamp.proto\"\234\001\n\005E" +
      "vent\0223\n\017event_timestamp\030\001 \001(\0132\032.google.p" +
      "rotobuf.Timestamp\0227\n\023ingestion_timestamp" +
      "\030\002 \001(\0132\032.google.protobuf.Timestamp\022%\n\007de" +
      "tails\030\003 \001(\0132\024.google.protobuf.Any*V\n\013Veh" +
      "icleType\022\007\n\003BUS\020\000\022\010\n\004TRAM\020\001\022\t\n\005TRAIN\020\002\022\t" +
      "\n\005FERRY\020\003\022\t\n\005METRO\020\004\022\010\n\004UBUS\020\005\022\t\n\005ROBOT\020" +
      "\006B\031\n\027com.dxc.ptinsight.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_dxc_ptinsight_Event_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_dxc_ptinsight_Event_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_dxc_ptinsight_Event_descriptor,
        new java.lang.String[] { "EventTimestamp", "IngestionTimestamp", "Details", });
    com.google.protobuf.AnyProto.getDescriptor();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
