# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ptinsight/common/proto/egress/flow.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ptinsight/common/proto/egress/flow.proto',
  package='com.dxc.ptinsight.egress',
  syntax='proto3',
  serialized_options=b'\n\036com.dxc.ptinsight.proto.egress',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n(ptinsight/common/proto/egress/flow.proto\x12\x18\x63om.dxc.ptinsight.egress\"5\n\rFlowDirection\x12\x15\n\rgeocells_edge\x18\x01 \x01(\x03\x12\r\n\x05\x63ount\x18\x02 \x01(\x05\x42 \n\x1e\x63om.dxc.ptinsight.proto.egressb\x06proto3'
)




_FLOWDIRECTION = _descriptor.Descriptor(
  name='FlowDirection',
  full_name='com.dxc.ptinsight.egress.FlowDirection',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='geocells_edge', full_name='com.dxc.ptinsight.egress.FlowDirection.geocells_edge', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='count', full_name='com.dxc.ptinsight.egress.FlowDirection.count', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=123,
)

DESCRIPTOR.message_types_by_name['FlowDirection'] = _FLOWDIRECTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FlowDirection = _reflection.GeneratedProtocolMessageType('FlowDirection', (_message.Message,), {
  'DESCRIPTOR' : _FLOWDIRECTION,
  '__module__' : 'ptinsight.common.proto.egress.flow_pb2'
  # @@protoc_insertion_point(class_scope:com.dxc.ptinsight.egress.FlowDirection)
  })
_sym_db.RegisterMessage(FlowDirection)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
