---
kafka:
  bootstrap_servers:
    - localhost:9092

sources:
  - type: mqtt
    broker:
      host: mqtt.hsl.fi
      port: 8883
    connector: hsl-realtime
    config:
      vehicle_types: bus,tram
      event_types: arr,dep
