---
logging:
  level: info
  console_producer: true

kafka:
  protobuf_format: json
  bootstrap_servers:
    - kafka-public-ip:9093

sources:
  - type: mqtt
    broker:
      host: mqtt.hsl.fi
      port: 8883
    processor: hsl-realtime
    config:
      vehicle_types: bus,tram,train
      event_types: vp
  - type: mqtt-recording
    file:
      bucket: mqtt-recordings
      key: mqtt.hsl.fi/2020-06-02T10-31-46.rec
    processor: hsl-realtime
    config:
      vehicle_types: bus,tram,train
      event_types: ars,dep
