---
logging:
  level: info

producer:
  type: console
  protobuf_format: json
  bootstrap_servers:
    - kafka-public-ip:9093

sources:
  - type: mqtt
    config:
      host: mqtt.hsl.fi
      port: 8883
    processor:
      type: hsl-realtime
      config:
        vehicle_types: bus,tram,train
        event_types: vp
  - type: mqtt-recording
    config:
      bucket: mqtt-recordings
      key: mqtt.hsl.fi/2020-06-02T10-31-46.rec
      latency_marker_interval: 1000
    processor:
      type: hsl-realtime
      config:
        h3_resolution: 9
        vehicle_types: bus,tram,train
        event_types: ars,dep
