---
- hosts: all
  roles:
    - ../../ansible/roles/common
    - ../../ansible/roles/python
  vars:
    - mqtt_host: mqtt.hsl.fi
    - mqtt_port: 8883
    - mqtt_topics: /hfp/v2/journey/#
    - recording_duration: 7d
  tasks:
    - name: create deploy directory
      file:
        path: /home/centos/deploy
        state: directory

    - name: upload Pipfile
      copy:
        src: "{{ playbook_dir }}/../{{ item }}"
        dest: /home/centos/deploy/
      loop:
        - Pipfile

    - name: upload application
      copy:
        src: "{{ playbook_dir }}/../{{ item }}"
        dest: /home/centos/deploy/
        mode: a+x
      loop:
        - record.py
        - replay.py
        - analyze.py
        - record_and_upload.sh

    - name: install pipenv
      command:
        cmd: pip3 install --user pipenv

    - name: install dependencies
      command:
        cmd: pipenv install
        chdir: "/home/centos/deploy"
