---
- name: add Flink user
  become: true
  user:
    name: flink

- name: check Flink installation
  become: true
  command: /opt/flink/bin/flink -v
  failed_when: no
  register: flink_version

- name: install Flink
  become: true
  block:
    - name: find Flink mirror
      uri:
        url: https://www.apache.org/dyn/closer.cgi?as_json
        return_content: yes
      register: flink_mirror

    - name: download and untar Flink
      unarchive:
        src: "{{ flink_mirror.json.preferred }}/flink/flink-1.10.1/flink-1.10.1-bin-scala_2.11.tgz"
        dest: /opt
        remote_src: yes

    - name: add generic Flink symlink
      file:
        src: /opt/flink-1.10.1
        dest: /opt/flink
        state: link

    - name: set Flink permissions
      file:
        path: /opt/flink
        state: directory
        recurse: yes
        owner: flink
        group: flink
  when: >
    flink_version.rc != 0 or not flink_version.stdout is match('Version: 1.10.1')

- name: start Flink cluster
  become: true
  # su instead of become_user is necessary, otherwise cluster shuts down after Ansible is done, nohup does not work
  command: su -c "/opt/flink/bin/start-cluster.sh" flink
