---
- name: add Flink user
  become: true
  user:
    name: flink

- name: check Flink installation
  become: true
  command: /opt/flink/bin/flink -v
  failed_when: no
  register: flink_version

- name: install Flink
  become: true
  block:
    - name: find Flink mirror
      uri:
        url: https://www.apache.org/dyn/closer.cgi?as_json
        return_content: yes
      register: flink_mirror

    - name: download and untar Flink
      unarchive:
        src: "{{ flink_mirror.json.preferred }}/flink/flink-1.10.1/flink-1.10.1-bin-scala_2.11.tgz"
        dest: /opt
        remote_src: yes

    - name: add generic Flink symlink
      file:
        src: /opt/flink-1.10.1
        dest: /opt/flink
        state: link

    - name: set Flink permissions
      file:
        path: /opt/flink
        state: directory
        recurse: yes
        owner: flink
        group: flink
    
  when: >
    flink_version.rc != 0 or not flink_version.stdout is match('Version: 1.10.1')

- name: Copy Flink job manager service file
  become: true
  template:
    src: flink-jobmanager.service.j2
    dest: /usr/lib/systemd/system/flink-jobmanager.service

- name: Copy Flink task manager service file
  become: true
  template:
    src: flink-taskmanager.service.j2
    dest: /usr/lib/systemd/system/flink-taskmanager.service

- name: reload systemd
  become: true
  systemd:
      daemon_reload: yes

- name: upload properties
  become: true
  template:
    src: flink-conf.yaml.j2
    dest: '/opt/flink/conf/flink-conf.yaml'
  notify:
    - restart the Flink job manager service
    - restart the Flink task manager service

- meta: flush_handlers

- name: start the Flink job manager service
  become: true
  service:
    name: flink-jobmanager
    state: started
    enabled: yes
  when: is_job_manager

- name: start the Flink task manager service
  become: true
  service:
    name: flink-taskmanager
    state: started
    enabled: yes
