---
- name: set up topics
  become: true
  become_user: kafka
  run_once: true
  command: "/opt/kafka/bin/kafka-topics.sh --create --zookeeper {{ zookeeper_servers | join(',') }} --replication-factor 3 --partitions {{ num_partitions }} --if-not-exists --topic {{ item }}"
  loop:
    - input.arrival
    - input.departure
    - input.vehicle-position
    - analytics.vehicle-count
    - analytics.delay-statistics
    - analytics.flow-direction
    - analytics.final-stop-count
    - analytics.emergency-stop-table
    - analytics.emergency-stop-streaming
