---
- name: set up topics
  become: true
  become_user: kafka
  run_once: true
  command: "/opt/kafka/bin/kafka-topics.sh --create --zookeeper {{ zookeeper_servers | join(',') }} --replication-factor 3 --partitions 1 --if-not-exists --topic {{ item }}"
  loop:
    - ingress.arrival
    - ingress.departure
    - ingress.vehicle-position
    - egress.arrival-count
    - egress.vehicle-count
    - egress.delay-statistics
    - egress.flow-direction
    - egress.final-stop-count
    - egress.emergency-stop
