---
- name: set up all hosts
  hosts: all
  tags: setup
  roles:
    - ../../ansible/roles/common

- name: set up mosquitto host
  hosts: mosquitto
  tags: setup
  roles:
    - ../../ansible/roles/mosquitto

- name: set up simulation host
  hosts: simulation
  vars:
    - simulation_source_path: "{{playbook_dir}}/../simulation/"
  roles:
    - { role: ../../ansible/roles/python,
        tags: setup }
    - { role: simulation,
        tags: deploy }

- name: set up a Flink host
  hosts: flink
  vars:
    - job_source_path: "{{playbook_dir}}/../carpool_service/"
  roles:
    - { role: ../../ansible/roles/flink,
        tags: setup }
    - { role: carpool_service,
        tags: deploy }
