---
- name: set up all hosts
  hosts: all
  roles:
    - { role: ../../ansible/roles/common,
        tags: setup }

- name: set up a Flink host
  hosts: flink
  vars:
    - application_source_path: "{{playbook_dir}}/../application/"
  roles:
    - { role: ../../ansible/roles/flink,
        tags: [ setup, flink ] }
    - { role: ../../ansible/roles/kafka,
        tags: [ setup, kafka ] }
    - { role: application,
        tags: deploy }
