---
- name: set up a Flink host
  hosts: instance
  vars:
    - application_source_path: "{{playbook_dir}}/../application/"
  roles:
    - { role: ../../ansible/roles/flink,
        tags: setup }
    - { role: application,
        tags: deploy }
